name = "Soundcore Q20i"
mac_address = "00:00:00:00:30:04"
rfcomm_uuid = "0CF12D31-FAC3-4553-BD80-D6832E7B3004"

[[responses]]
# State update
command = [1, 1]
response = [
    0x4,
    0x0,
    0x30,
    0x30,
    0x2e,
    0x32,
    0x36,
    0x33,
    0x30,
    0x30,
    0x34,
    0x38,
    0x39,
    0x30,
    0x39,
    0x35,
    0x62,
    0x65,
    0x32,
    0x33,
    0x38,
    0x62,
    0x30,
    0xfe,
    0xfe,
    0x78,
    0x78,
    0x78,
    0x78,
    0x78,
    0x78,
    0x78,
    0x78,
    0x78,
    0x78,
    0x0,
    0x3f,
    0x2,
    0xff,
    0x1,
    0xff,
    0x1,
    0x31,
    0xff,
    0xff,
    0xff,
    0xff,
    0xff,
    0xff,
    0xff,
    0xff,
    0xff,
    0xff,
    0xff,
    0xff,
    0xff,
    0xff,
    0xff,
    0xff,
    0xff,
    0xff,
]
