name = "Soundcore Space One"
rfcomm_uuid = "0CF12D31-FAC3-4553-BD80-D6832E7B3035"

[[responses]]
# State update
command = [1, 1]
response = [
    3,
    255,
    48,
    54,
    46,
    56,
    55,
    51,
    48,
    51,
    53,
    55,
    48,
    53,
    48,
    50,
    56,
    56,
    65,
    57,
    68,
    70,
    52,
    0,
    0,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    0,
    30,
    255,
    0,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    0,
    0,
    0,
    0,
    0,
    0,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    0,
    0,
    0,
    4,
    4,
    7,
    3,
    0,
    80,
    0,
    0,
    1,
    5,
    0,
    1,
    0,
    0,
    0,
    49,
    1,
    0,
    1,
    0,
    1,
    1,
    0,
    90,
    0,
    1,
    1,
    0,
    0,
    0,
]
