name = "Soundcore Space Q45"
rfcomm_uuid = "0CF12D31-FAC3-4553-BD80-D6832E7B3040"

[[responses]]
command = [1, 1]
response = [
    3,
    255,
    48,
    50,
    46,
    51,
    52,
    51,
    48,
    52,
    48,
    49,
    65,
    49,
    65,
    50,
    70,
    67,
    67,
    69,
    69,
    69,
    56,
    17,
    0,
    150,
    140,
    110,
    110,
    130,
    150,
    160,
    170,
    120,
    0,
    122,
    122,
    118,
    119,
    121,
    122,
    122,
    126,
    120,
    0,
    4,
    4,
    7,
    7,
    0,
    80,
    0,
    1,
    1,
    5,
    255,
    0,
    0,
    255,
    0,
    49,
    0,
    1,
    255,
    0,
    1,
    0,
    0,
    90,
    0,
    1,
    1,
    1,
    0,
    17,
    50,
    1,
    1,
    143,
    143,
    128,
    138,
    150,
    150,
    143,
    143,
    60,
    60,
    143,
    143,
    128,
    138,
    150,
    150,
    143,
    143,
    60,
    60,
    100,
    152,
    140,
    205,
    0,
    143,
    143,
    128,
    138,
    150,
    150,
    143,
    143,
    60,
    60,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    122,
    122,
    119,
    121,
    122,
    122,
    121,
    123,
    114,
    0,
    17,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
]
