name = "soundcore A20i"
mac_address = "00:00:00:00:39:48"
rfcomm_uuid = "0CF12D31-FAC3-4553-BD80-D6832E7B3948"

[[responses]]
# State update
command = [1, 1]
response = [
    0,    # host device
    1,    # tws connected
    5,    # left battery
    5,    # right battery
    0,    # left battery charging
    0,    # right battery charging
    50,   # Left firmware start
    52,
    46,
    53,
    54,   # Left firmware end
    50,   # Right firmware start
    52,
    46,
    53,
    54,   # Right firmware end
    51,   # Serial number start
    57,
    52,
    56,
    49,
    57,
    70,
    70,
    49,
    68,
    67,
    65,
    66,
    65,
    50,
    67,   # Serial number end
    2,    # Equalizer Profile
    0,    # Equalizer Profile
    160,  # Left volume adjustments start
    150,
    130,
    120,
    120,
    120,
    120,
    120,
    120,
    0,    # Left volume adjustments end
    0,    # Right volume adjustments start
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,    # Right volume adjustments end
    14,
    1,    # Left single tap enabled
    0xF6, # Left single tap action
    1,    # Right single tap enabled
    0xF3, # Right single tap action
    1,    # Left double tap enabled
    0x6F, # Left double tap action
    1,    # Right double tap enabled
    0x62, # Right double tap action
    1,    # Left tap and hold enabled
    0x31, # Left tap and hold action
    1,    # Right tap and hold enabled
    0x30, # Right tap and hold action
    255,
    255,
    255,
    97,
    0,
    1,    # Touch Tone
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
]
