name = "Soundcore Life Note 3S"
rfcomm_uuid = "0CF12D31-FAC3-4553-BD80-D6832E7B3945"

[[responses]]
# State update
command = [1, 1]
response = [
    0,
    1,
    4,
    5,
    0,
    0,
    48,
    48,
    46,
    48,
    48,
    48,
    48,
    46,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    48,
    0,
    0,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    1,
    0x66, # Left double tap
    1,
    0x55, # Left long press
    1,
    0x33, # Right double tap
    1,
    0x22, # Right long pres
    1,
    0x1,  # Left single press
    1,
    0x0,  # Right single press
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
]
