name = "Soundcore A30i"
rfcomm_uuid = "0CF12D31-FAC3-4553-BD80-D6832E7B3958"

[[responses]]
# State update
command = [1, 1]
response = [
    0,
    1,
    7,
    6,
    255,
    255,
    48,
    49,
    46,
    52,
    57,
    48,
    49,
    46,
    52,
    55,
    51,
    57,
    53,
    56,
    53,
    56,
    70,
    68,
    54,
    67,
    53,
    66,
    49,
    56,
    50,
    48,
    2,
    0,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    10,
    246,
    246,
    98,
    99,
    255,
    244,
    68,
    68,
    53,
    0,
    81,
    0,
    1,
    0,
    255,
    2,
    49,
    1,
    1,
    0,
    1,
    0,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
]
