name = "Soundcore Liberty 4 Pro"
mac_address = "00:00:00:00:39:54"
rfcomm_uuid = "0CF12D31-FAC3-4553-BD80-D6832E7B3954"

[[responses]]
# State update
command = [1, 1]
response = [
    0,
    1,
    99,
    100,
    0,
    0,
    48,
    51,
    46,
    50,
    57,
    48,
    51,
    46,
    50,
    57,
    51,
    57,
    53,
    52,
    68,
    69,
    55,
    55,
    53,
    49,
    56,
    65,
    57,
    68,
    70,
    52,
    48,
    50,
    46,
    53,
    56,
    9,
    244,
    157,
    138,
    83,
    43,
    186,
    254,
    254,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    0,
    1,
    145,
    147,
    139,
    141,
    122,
    111,
    105,
    100,
    60,
    60,
    145,
    147,
    139,
    141,
    122,
    111,
    105,
    100,
    60,
    60,
    0,
    0,
    0,
    0,
    1,
    145,
    147,
    139,
    130,
    122,
    133,
    133,
    114,
    60,
    60,
    145,
    147,
    139,
    130,
    122,
    133,
    133,
    114,
    60,
    60,
    0,
    0,
    10,
    102,
    102,
    50,
    51,
    255,
    255,
    68,
    68,
    51,
    2,
    6,
    0,
    0,
    255,
    1,
    255,
    0,
    0,
    0,
    0,
    94,
    1,
    110,
    1,
    1,
    0,
    0,
    1,
    0,
    1,
    95,
    0,
    0,
    1,
    1,
    0,
    0,
    0,
    110,
    1,
    0,
    1,
    0,
    0,
    255,
    0,
    0,
    17,
    17,
]
