name = "Soundcore Liberty 5"
mac_address = "00:00:00:00:39:57"
rfcomm_uuid = "0CF12D31-FAC3-4553-BD80-D6832E7B3957"

[[responses]]
# State update
command = [1, 1]
response = [
    0x00,
    0x01,
    0x08,
    0x08,
    0x00,
    0x00,
    0x30,
    0x33,
    0x2e,
    0x39,
    0x30,
    0x30,
    0x33,
    0x2e,
    0x39,
    0x30,
    0x33,
    0x39,
    0x35,
    0x37,
    0x46,
    0x34,
    0x39,
    0x44,
    0x38,
    0x41,
    0x43,
    0x32,
    0x30,
    0x33,
    0x33,
    0x34,
    0x30,
    0x30,
    0x2e,
    0x30,
    0x30,
    0x02,
    0x00,
    0x00,
    0x78,
    0x78,
    0x78,
    0x78,
    0x78,
    0x78,
    0x78,
    0x78,
    0x78,
    0x78,
    0xff,
    0xff,
    0xff,
    0xff,
    0xff,
    0xff,
    0xff,
    0xff,
    0xff,
    0xff,
    0x00,
    0x01,
    0x91,
    0x82,
    0x73,
    0x77,
    0x8b,
    0x93,
    0x8f,
    0x96,
    0x00,
    0x00,
    0x91,
    0x82,
    0x73,
    0x77,
    0x8b,
    0x93,
    0x8f,
    0x96,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x91,
    0x82,
    0x73,
    0x77,
    0x8b,
    0x93,
    0x8f,
    0x96,
    0x00,
    0x00,
    0x91,
    0x82,
    0x73,
    0x77,
    0x8b,
    0x93,
    0x8f,
    0x96,
    0x00,
    0x00,
    0x00,
    0x00,
    0x0a,
    0x66,
    0x66,
    0x32,
    0x33,
    0xff,
    0xff,
    0x44,
    0x44,
    0x33,
    0x00,
    0x50,
    0x00,
    0x00,
    0x00,
    0x00,
    0x00,
    0x33,
    0x01,
    0x01,
    0x00,
    0x01,
    0x01,
    0x02,
    0x00,
    0x5a,
    0x00,
    0x00,
    0x01,
    0x00,
    0x00,
    0xff,
    0x01,
    0x00,
    0x00,
    0x01,
    0x01,
    0x00,
    0x01,
    0xff,
    0xff,
    0xff,
    0x03,
    0xff,
    0xff,
]

[[responses]]
# DB level
command = [32, 3]
response = [
    80, # current db level
]

[[responses]]
command = [16, 151]
response = [1]

[[responses]]
command = [3, 148]
response = [1]

[[responses]]
command = [5, 1]
response = [
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
]

[[responses]]
command = [5, 129]
response = [1]
