name = "soundcore Sport X20"
mac_address = "00:00:00:00:39:68"
rfcomm_uuid = "0CF12D31-FAC3-4553-BD80-D6832E7B3968"

[[responses]]
command = [1, 1]
# State update
response = [
    0,
    1,
    5,
    5,
    0,
    0,
    48,
    49,
    46,
    54,
    53,
    48,
    49,
    46,
    54,
    53,
    51,
    57,
    54,
    56,
    98,
    48,
    51,
    56,
    101,
    50,
    54,
    98,
    98,
    101,
    57,
    97,
    0,
    0,
    0,
    0,
    0,
    2,
    254,
    254,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    120,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    48,
    1,
    1,
    135,
    114,
    140,
    142,
    150,
    145,
    166,
    134,
    60,
    60,
    135,
    114,
    140,
    142,
    150,
    145,
    166,
    134,
    60,
    60,
    255,
    255,
    255,
    255,
    1,
    151,
    151,
    140,
    143,
    151,
    145,
    165,
    134,
    60,
    0,
    151,
    151,
    140,
    143,
    151,
    145,
    165,
    134,
    60,
    0,
    0,
    0,
    8,
    97,
    102,
    48,
    51,
    68,
    68,
    55,
    0,
    50,
    1,
    0,
    0,
    255,
    54,
    1,
    0,
    1,
    0,
    1,
    2,
    1,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
]
