name = "soundcore Sleep A20"
mac_address = "00:00:00:00:66:11"
rfcomm_uuid = "0CF12D31-FAC3-4553-BD80-D6832E7B6611"

[[responses]]
command = [1, 1]
# State update
response = [
    1,
    1,
    9,
    9,
    48,
    49,
    46,
    53,
    48,
    48,
    49,
    46,
    53,
    48,
    54,
    54,
    49,
    49,
    70,
    52,
    57,
    68,
    56,
    65,
    50,
    55,
    53,
    54,
    53,
    67,
    4,
    0,
    150,
    150,
    100,
    100,
    120,
    140,
    150,
    160,
    120,
    0,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    6,
    221,
    51,
    17,
    0,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    255,
    0,
    0,
    2,
    120,
    0,
    0,
    255,
    255,
    255,
    1,
    1,
    0,
    49,
    0,
    2,
    0,
    4,
    0,
    114,
    138,
    5,
    0,
    0,
    0,
    0,
    0,
    2,
    1,
    109,
    138,
    5,
    0,
    0,
    0,
    0,
    0,
    2,
    2,
    90,
    138,
    5,
    0,
    0,
    0,
    0,
    0,
    2,
    3,
    101,
    138,
    5,
    0,
    0,
    0,
    0,
    0,
    2,
    1,
    3,
    0,
    1,
    8,
    0,
    0,
    0,
    0,
]
